/*
  # Create site_visits table

  Stores one row per website load so traffic can be counted from Supabase.
  Inserts are intended to happen through the `track-site-visit` Edge Function.
*/

CREATE TABLE IF NOT EXISTS public.site_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL DEFAULT '/',
  referrer TEXT,
  user_agent TEXT,
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_site_visits_created_at
  ON public.site_visits (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_site_visits_path
  ON public.site_visits (path);

ALTER TABLE public.site_visits ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.site_visits IS 'Tracks website load events recorded through the Supabase Edge Function.';
